add-bookings
Scandi7/java-shareit pull request #4
Opened 2024-12-02 07:42 UTC by Scandi7

2024-12-02 08:31 UTC, Scandi7 commented
Привет, Евгений, а можете подсказать, пожалуйста, вот у меня есть коммиты ef2cbd0, 9d1dce5 и т.д. Их можно как то удалить чтобы их не было видно на гитхаб? Допустим, чтобы в истории было только c423e5a и 579ba5b?

2024-12-02 16:51 UTC, EugeneLenkevich requested changes
Привет, Даниил! Спасибо за PR.

Вот сама работа выполнена круто, и транзакции расставлены, но так хочется всякую мелочевку поправить, а то как то диссонирует с самой работой :)

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Autowired
@Autowired

На конструкторе вроде как уже указывать аннотацию не надо, ее мы ставим на поля класса

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new RuntimeException("Только владелец может подтвердить или отклонить бронирование");
Как то слишком сурово тут кидать непроверяемое исключение, тут бы сделать свое, проверяемое. С помощью проверяемых исключений мы сообщаем другому коду что в бизнес-процессе есть такая ситуация и ее надо обработать. Непроверяемое же исключение - это ошибка в самом алгоритме :)

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                           @RequestParam(defaultValue = "ALL") String state) {
String state

А мы же тут можем использовать enum, проще и надежней :)

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "CURRENT":
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/exception/CommentNotFoundException.java
> +public class CommentNotFoundException extends RuntimeException {
То что комментарий не найден - это не ошибка, а ситуация в нашем бизнес-процессе, потому пусть тут будет проверяемое исключение :)
extends Exception

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/exception/ItemNotAvailableException.java
> +public class ItemNotAvailableException extends RuntimeException {
Ну и тут вряд ли подходит именно непроверяемое исключение :)

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +            "AND UPPER(i.name) LIKE UPPER(CONCAT('%', ?1, '%')) " +
?1

А вот с плейсхолдером :text все же наглядней, плюс в другом коде плейсхолдеры используются, и, в целом, лучше все делать единообразно :)

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .filter(booking -> booking.getEnd().isBefore(now))
.filter(booking -> booking.getEnd().isBefore(now))

А не проще было условие в sql-запрос добавить чтобы потом не дофильтровывать :)

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                            .filter(booking -> booking.getEnd().isBefore(now))
LocalDateTime lastBooking = bookingRepository.findLastBooking(item.getId(), now).stream()
                            .filter(booking -> booking.getEnd().isBefore(now))

В соседнем методе к тому же аналогичный запрос и аналогичная фильтрация, то есть дублирование кода :)

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .size() > 0;
То есть для проверки существования мы вытаскиваем все записи по условию и проверяем размер списка/ Не особо эффективно и опасно для случаев когда данных может быть много

Тут можно прикрутить exists-запрос

boolean existsByBooker...

https://stackoverflow.com/questions/30392129/spring-data-jpa-and-exists-query

2024-12-02 16:51 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            if (userRepository.findByEmail(userDto.getEmail()).isPresent()) {
Опять таки, 

boolean existsByEmail

к тому же ты этот подход и так используешь :)

2024-12-04 01:56 UTC, Scandi7 commented
> Привет, Даниил! Спасибо за PR.
> 
> Вот сама работа выполнена круто, и транзакции расставлены, но так хочется всякую мелочевку поправить, а то как то диссонирует с самой работой :)

И вам спасибо за ревью, исправил замечания

2024-12-04 01:56 UTC, Scandi7 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Autowired
а я читал, что наоборот не рекомендуется использовать @Autowired на поля, а лучше через сеттер или конструктор

2024-12-04 01:59 UTC, Scandi7 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "CURRENT":
звучит интересно, попробую реализовать чуть попозже, спасибо

2024-12-04 04:45 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Autowired
Тут не совсем про это
есть два способа 
- @Autowired+setter
- конструктор

2024-12-04 04:49 UTC, EugeneLenkevich commented
>  коммиты [ef2cbd0](https://github.com/Scandi7/java-shareit/commit/ef2cbd001f3a6758ae6bd9a9dc75b96480524f1e), [9d1dce5](https://github.com/Scandi7/java-shareit/commit/9d1dce53903963af943a3f001b4937bb6e168add) и т.д. Их можно как то удалить чтобы их не было видно на гитхаб? 

Ну вообще можно. Создать ветку от основной до этих комитов, перенести нужные комиты, а дальше перезаписать основную ветку новой. Но это решение проблемы через грубую силу, можно делов наворотить и в реальном проекте за такое по голове не погладят потом проще оставить как есть, они же сами по себе в истории не мешают  :)

2024-12-04 04:51 UTC, EugeneLenkevich approved these changes
По правкам - нагляднее и красивее же стало, супер :)

2024-12-04 04:52 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Autowired
Лишь к тому что аннотацию можно убрать, через конструктор и без нее должно работать

2024-12-07 05:10 UTC, merged