ТЗ 16
Scandi7/java-shareit pull request #5
Opened 2024-12-08 11:36 UTC by Scandi7

2024-12-11 19:45 UTC, EugeneLenkevich requested changes
Привет, Даниил! Спасибо за PR.

Все ок и даже клиенты сделаны через конфигурации. Один момент только - в нескольких местах код закомментированный, давай его почикаем, все таки захлямляет

![image](https://github.com/user-attachments/assets/61d762b8-3e5a-4110-b0c0-e4fa68ce85a1)

2024-12-11 19:45 UTC, EugeneLenkevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	/*	@GetMapping
Ну и убрать бы этот закомментированный код, зачем его хранить :)

2024-12-11 19:45 UTC, EugeneLenkevich commented on server/src/test/java/ru/practicum/shareit/exception/GlobalExceptionHandlerTest.java
> +class GlobalExceptionHandlerTest {
Ммм, а надо ли писать тест на эту штуку, мы по сути делаем тестируем сам спринг :)
В таком случае лучше тестировать то что контроллеры отдают нужные ответы (по сути дела приемочные тесты при сборке у нас это и делают)

2024-12-11 20:00 UTC, Scandi7 commented on server/src/test/java/ru/practicum/shareit/exception/GlobalExceptionHandlerTest.java
> +class GlobalExceptionHandlerTest {
по идее такой тест не нужен, но если не писать, то % покрытия не хватит, который стоит при проверке

2024-12-12 02:58 UTC, EugeneLenkevich commented on server/src/test/java/ru/practicum/shareit/exception/GlobalExceptionHandlerTest.java
> +class GlobalExceptionHandlerTest {
Ох уж это покрытие

2024-12-12 02:59 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-12-12 08:53 UTC, merged